version: '3.8'
services:
  app:
    container_name: docker_node
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
  mongo:
    container_name: docker_mongo
    image: mongo
    ports:
      - '27017:27017'